// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbxdcxlwryzcxiujafls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRieGRjeGx3cnl6Y3hpdWphZmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDkzNzEsImV4cCI6MjA2ODUyNTM3MX0.gckINmb6WLi3EXewsjDTVGG0EtUEEjJyLgPR1uzxQfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});